name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          #- 22.x # `tsc` currently segfaults on Node v22. Possibly due to:
          # https://github.com/nodejs/node/issues/52797

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      shell: bash
      run: |
        npm ci
        npm run build
        npm test
      env:
        CI: true
