name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          #- 22.x # Currently segfaults? https://github.com/fortanix/openapi-to-effect/actions/runs/9235995285/job/25411385965

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      shell: bash
      run: |
        npm ci
        npm run build
        npm test
      env:
        CI: true
